# Generated by Django 4.1.7 on 2023-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0003_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
